### ISSUE TITLE
net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location

### ISSUE THREAD

**Issue by Hurricane144** [Edivad99/ExtraStorage#14]
Well it crashes

**Configuration**
Mod version:1.16.4-120
Forge version:35.1.4
Minecraft version:1.16.4
Refined Storage version:1.2.0
Are you playing on server?:
no
**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
Mod File: ExtraStorage-1.16.4-1.2.0.jar
	Failure message: Extra Storage (extrastorage) has failed to load correctly
		net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: extrastorage:ıron_crafter
	Mod Version: 1.2.0
	Mod Issue URL: NOT PROVIDED
	Exception message: net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: extrastorage:ıron_crafter
Stacktrace:
	at net.minecraft.util.ResourceLocation.<init>(ResourceLocation.java:33) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.util.ResourceLocation.<init>(ResourceLocation.java:42) ~[?:?] {re:classloading,re:mixin}
	at net.minecraftforge.registries.DeferredRegister.register(DeferredRegister.java:114) ~[forge:?] {re:classloading}
	at edivad.extrastorage.setup.Registration.init(Registration.java:134) ~[extrastorage:1.2.0] {re:classloading}
	at edivad.extrastorage.Main.<init>(Main.java:30) ~[extrastorage:1.2.0] {re:classloading}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_271] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_271] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_271] {}
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_271] {}
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_271] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:35.1] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_271] {}

**Comment by Edivad99** [comment]
#13
