### ISSUE TITLE
1.16.5 Conflict with Cable Tiers

### ISSUE THREAD

**Issue by Hiranus** [Edivad99/ExtraStorage#57]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This mod conflicts with Cable Tiers mod in a very strange way. If both this mod and Cable Tiers is present then most stuff from Cable tiers has problems working correctly. Requesters simply don't work and don't store requested number. importers & exporters cant be put into fluid mode etc.
https://github.com/starforcraft/Cable-Tiers/issues/34
If this mod is removed everything starts working normally.

### How can I reproduce this bug or crash?

1. Get both this mod and Cable Tiers running at the same time.
2. try to use some stuff from Cable Tiers - requesters or importers/exporters in fluid mode are good examples.
3. check log

### Configuration

```markdown
- Mod version:1.6.1
- Cable Tiers version: 1.16.5-0.544
- Refined Storage version:1.9.17
- Forge version:36.2.29
- Minecraft version:1.16.5
```

### Relevant log output

```shell
[28Mar2022 23:31:04.272] [Server thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Server
java.lang.ClassCastException: class com.YTrollman.CableTiers.node.TieredRequesterNetworkNode cannot be cast to class com.refinedmods.refinedstorage.tile.config.IAccessType (com.YTrollman.CableTiers.node.TieredRequesterNetworkNode and com.refinedmods.refinedstorage.tile.config.IAccessType are in unnamed module of loader cpw.mods.modlauncher.TransformingClassLoader @f348e10)
	at com.refinedmods.refinedstorage.tile.config.IAccessType.lambda$createParameter$1(IAccessType.java:11) ~[refinedstorage:1.9.17]
	at com.refinedmods.refinedstorage.network.tiledata.TileDataParameterUpdateMessage.lambda$handle$0(TileDataParameterUpdateMessage.java:53) ~[refinedstorage:1.9.17]
	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) ~[forge:?]
	at com.refinedmods.refinedstorage.network.tiledata.TileDataParameterUpdateMessage.handle(TileDataParameterUpdateMessage.java:46) ~[refinedstorage:1.9.17]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) ~[forge:?]
	at java.util.Optional.ifPresent(Optional.java:176) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) ~[forge:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[forge:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[forge:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:86) ~[forge:?]
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:91) ~[forge:?]
	at java.util.Optional.map(Optional.java:258) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:91) ~[forge:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:1413) ~[?:?]
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:42) ~[?:?]
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:12) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:696) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

### Anything else?
https://www.curseforge.com/minecraft/mc-mods/cable-tiers

**Comment by Edivad99** [comment]
I know, nothing that i can do

**Comment by Hiranus** [comment]
I already assumed its in Cable Tiers side, but maybe you could together go through the code to figure what is it about, since you both create addon for same mod.

**Comment by Edivad99** [comment]
We should solve this problem. I close the issue since there is no trace of my mod in the log

**Comment by KuroPeach** [comment]
Same problem, this is on the ATM6SKY mod pack, it should be the reason why both mods add more I/O cables to the RS

[12May2022 16:33:46.224] [Server thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Server
java.lang.ClassCastException: class edivad.extrastorage.nodes.AdvancedImporterNetworkNode cannot be cast to class com.refinedmods.refinedstorage.tile.config.IAccessType (edivad.extrastorage.nodes.AdvancedImporterNetworkNode and com.refinedmods.refinedstorage.tile.config.IAccessType are in unnamed module of loader cpw.mods.modlauncher.TransformingClassLoader @1239c268)
	at com.refinedmods.refinedstorage.tile.config.IAccessType.lambda$createParameter$1(IAccessType.java:11) ~[refinedstorage:1.9.17]
	at com.refinedmods.refinedstorage.network.tiledata.TileDataParameterUpdateMessage.lambda$handle$0(TileDataParameterUpdateMessage.java:53) ~[refinedstorage:1.9.17]
	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) ~[forge:?]
	at com.refinedmods.refinedstorage.network.tiledata.TileDataParameterUpdateMessage.handle(TileDataParameterUpdateMessage.java:46) ~[refinedstorage:1.9.17]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) ~[forge:?]
	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) ~[forge:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[forge:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[forge:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:86) ~[forge:?]
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:91) ~[forge:?]
	at java.util.Optional.map(Optional.java:265) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:91) ~[forge:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:1413) ~[?:?]
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:42) ~[?:?]
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:12) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:697) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
