### ISSUE TITLE
Patterns disappearing from crafters

### ISSUE THREAD

**Issue by James31047** [Edivad99/ExtraStorage#72]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Logged on to ATM8 single player world today and all of my patterns are missing from a one of my two Netherite Crafters. I updated the pack from version 8-1.0.23 to 8-1.0.25 recently, which may be related.

### How can I reproduce this bug or crash?

Play a single player world in ATM8. Update the mod pack and see if patterns disappear.

### Configuration

```markdown
- Mod version:1.19.2-3.0.1
- Refined Storage version:1.11.6
- Forge version:43.2.14
- Minecraft version:1.19.2
```

**Comment by Edivad99** [comment]
I can't reproduce this bug. It's strange because I rely on the methods of Refined Storage and there shouldn't be this problem. If you tell me what you usually do to cause this it would be greatly appreciated

**Comment by James31047** [comment]
I believe it happened when I updated the ATM8 modpack from 8-1.0.23 to 8-1.0.25.

**Comment by ehertlein** [comment]
I just ran into this as well with an Iron Crafter, all the patterns were deleted. I don't remember if it was around the time I updated ATM8 from 1.0.25 to 1.0.27 but I did do that recently.

**Comment by jinkhya** [comment]
Hello, had the same issue on TNP limitless 7. I believe this is related : 
https://github.com/starforcraft/Creative-Crafter/issues/16
I posted a log on that issue tracker about possibly fastsuite being involved Which could be possible considering ATM8 and TNP packs include fastsuite. I just need somebody more advanced than me at reading logs to confirm that's the problem and then I can report it to fastsuite :)

**Comment by xenonmb** [comment]
i got the same problem here in the all the mods 9 modpack version 0.1.12. So far it happened two times, and always to the same netherite crafter

**Comment by Freakyman403** [comment]
> i got the same problem here in the all the mods 9 modpack version 0.1.12. So far it happened two times, and always to the same netherite crafter

i have had this issue where it seems any crafter of this mod that has Mekanism patterns vanishes, i tested with RS Crafters and so far they have remained, all my other crafters that have different items have not once vanished, so that is the only thing i can link towards the vanishing patterns.

**Comment by Freakyman403** [comment]
> > i got the same problem here in the all the mods 9 modpack version 0.1.12. So far it happened two times, and always to the same netherite crafter
> 
> i have had this issue where it seems any crafter of this mod that has Mekanism patterns vanishes, i tested with RS Crafters and so far they have remained, all my other crafters that have different items have not once vanished, so that is the only thing i can link towards the vanishing patterns.

ive done more testing with mekanism and patterns and i have so far i have found out the patterns that affect them is the mekanism pipe/cable recipes done multiple restarts and other mekanism items have stayed and no other pattern has disappeared from my crafters except the crafter with just mekanism pipe/cable recipes.

**Comment by Edivad99** [comment]
Thanks, I will look at it

**Comment by Freakyman403** [comment]
> Thanks, I will look at it

did some more digging to help as best as i can, this issue also vanishes with normal refined storage, and its only when the pattern is a mekanism pipe/cable.

**Comment by Edivad99** [comment]
But then is it strange. Why would mekanism have these problems? They are normal recipes

**Comment by Freakyman403** [comment]
> But then is it strange. Why would mekanism have these problems? They are normal recipes

Well i have submitted tickets to both Mekanism and Refined Storage. since the issue is tied to either side.

**Comment by xBlackPoison357x** [comment]
Also getting this issue, Running All the mods 9 pack.

**Comment by raoulvdberge** [comment]
I can't reproduce it either.

**Comment by K1kk0m4n** [comment]
Same issue on ATM 9. Seems like my netherite crafter started doing this after recent patch to version 0.2.21
Only crafter doing this was containing patterns for powah and some mekanism upgrades, also redstone block.

**Comment by Sandriell** [comment]
Experience this as well. And while I do have Mekanism, I have had Diamond Crafters with with nothing but vanilla recipe patterns in them, also get wiped/vanish.

**Comment by baalus** [comment]
I have the same problem with ATM 8 v1.1.0.

I see that is a exception during start:
```
[03Mar2024 08:34:49.806] [Server thread/ERROR] [com.refinedmods.refinedstorage.apiimpl.network.NetworkNodeManager/]: Could not read network node
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.util.ConcurrentModificationException: java.util.ConcurrentModificationException
	at shadows.fastsuite.AuxRecipeManager.m_44015_(AuxRecipeManager.java:51) ~[FastSuite-1.19.2-4.1.1.jar%23670!/:4.1.1]
	at com.refinedmods.refinedstorage.apiimpl.autocrafting.CraftingPatternFactory.redirect$dpn000$getRecipe(CraftingPatternFactory.java:537) ~[refinedstorage-1.11.7.jar%23810!/:1.11.7]
	at com.refinedmods.refinedstorage.apiimpl.autocrafting.CraftingPatternFactory.create(CraftingPatternFactory.java:60) ~[refinedstorage-1.11.7.jar%23810!/:1.11.7]
	at com.refinedmods.refinedstorage.item.PatternItem.create(PatternItem.java:294) ~[refinedstorage-1.11.7.jar%23810!/:1.11.7]
	at edivad.extrastorage.nodes.AdvancedCrafterNetworkNode.invalidateSlot(AdvancedCrafterNetworkNode.java:117) ~[ExtraStorage-1.19.2-3.0.1.jar%23663!/:3.0.1]
	at edivad.extrastorage.nodes.AdvancedCrafterNetworkNode.invalidate(AdvancedCrafterNetworkNode.java:105) ~[ExtraStorage-1.19.2-3.0.1.jar%23663!/:3.0.1]
	at edivad.extrastorage.nodes.AdvancedCrafterNetworkNode.read(AdvancedCrafterNetworkNode.java:177) ~[ExtraStorage-1.19.2-3.0.1.jar%23663!/:3.0.1]
	at edivad.extrastorage.setup.ModSetup.readAndReturn(ModSetup.java:60) ~[ExtraStorage-1.19.2-3.0.1.jar%23663!/:3.0.1]
	at edivad.extrastorage.setup.ModSetup.lambda$init$0(ModSetup.java:36) ~[ExtraStorage-1.19.2-3.0.1.jar%23663!/:3.0.1]
	at com.refinedmods.refinedstorage.apiimpl.network.NetworkNodeManager.load(NetworkNodeManager.java:59) ~[refinedstorage-1.11.7.jar%23810!/:1.11.7]
	at com.refinedmods.refinedstorage.apiimpl.API.lambda$getNetworkNodeManager$1(API.java:134) ~[refinedstorage-1.11.7.jar%23810!/:1.11.7]
	at net.minecraft.world.level.storage.DimensionDataStorage.m_164868_(DimensionDataStorage.java:70) ~[client-1.19.2-20220805.130853-srg.jar%23909!/:?]
	at net.minecraft.world.level.storage.DimensionDataStorage.m_164858_(DimensionDataStorage.java:54) ~[client-1.19.2-20220805.130853-srg.jar%23909!/:?]
	at net.minecraft.world.level.storage.DimensionDataStorage.m_164861_(DimensionDataStorage.java:39) ~[client-1.19.2-20220805.130853-srg.jar%23909!/:?]
	at com.refinedmods.refinedstorage.apiimpl.API.getNetworkNodeManager(API.java:132) ~[refinedstorage-1.11.7.jar%23810!/:1.11.7]
	at com.refinedmods.refinedstorage.blockentity.NetworkNodeBlockEntity.m_6339_(NetworkNodeBlockEntity.java:109) ~[refinedstorage-1.11.7.jar%23810!/:1.11.7]
	at net.minecraft.world.level.chunk.LevelChunk.m_142169_(LevelChunk.java:354) ~[client-1.19.2-20220805.130853-srg.jar%23909!/:?]
	at net.minecraft.world.level.chunk.storage.ChunkSerializer.m_196900_(ChunkSerializer.java:424) ~[client-1.19.2-20220805.130853-srg.jar%23909!/:?]
	at net.minecraft.world.level.chunk.LevelChunk.m_62952_(LevelChunk.java:429) ~[client-1.19.2-20220805.130853-srg.jar%23909!/:?]
	at net.minecraft.server.level.ChunkMap.mixinextras$bridge$m_62952_$140(ChunkMap.java) ~[client-1.19.2-20220805.130853-srg.jar%23909!/:?]
	at net.minecraft.server.level.ChunkMap.wrapOperation$zgb000$setCurrentLoadingThenPostLoad(ChunkMap.java:1854) ~[client-1.19.2-20220805.130853-srg.jar%23909!/:?]
	at net.minecraft.server.level.ChunkMap.m_214854_(ChunkMap.java:691) ~[client-1.19.2-20220805.130853-srg.jar%23909!/:?]
	at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162) ~[datafixerupper-5.0.28.jar%23126!/:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-5.0.28.jar%23126!/:?]
	at com.mojang.datafixers.util.Either.mapLeft(Either.java:162) ~[datafixerupper-5.0.28.jar%23126!/:?]
	at net.minecraft.server.level.ChunkMap.m_214851_(ChunkMap.java:675) ~[client-1.19.2-20220805.130853-srg.jar%23909!/:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[client-1.19.2-20220805.130853-srg.jar%23909!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.19.2-20220805.130853-srg.jar%23909!/:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_6367_(ServerChunkCache.java:535) ~[client-1.19.2-20220805.130853-srg.jar%23909!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.19.2-20220805.130853-srg.jar%23909!/:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_7245_(ServerChunkCache.java:543) ~[client-1.19.2-20220805.130853-srg.jar%23909!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_8466_(ServerChunkCache.java:267) ~[client-1.19.2-20220805.130853-srg.jar%23909!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:751) ~[client-1.19.2-20220805.130853-srg.jar%23909!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:740) ~[client-1.19.2-20220805.130853-srg.jar%23909!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[client-1.19.2-20220805.130853-srg.jar%23909!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:726) ~[client-1.19.2-20220805.130853-srg.jar%23909!/:?]
	at net.minecraft.server.MinecraftServer.m_129940_(MinecraftServer.java:447) ~[client-1.19.2-20220805.130853-srg.jar%23909!/:?]
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:302) ~[client-1.19.2-20220805.130853-srg.jar%23909!/:?]
	at net.minecraft.client.server.IntegratedServer.m_7038_(IntegratedServer.java:62) ~[client-1.19.2-20220805.130853-srg.jar%23909!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:625) ~[client-1.19.2-20220805.130853-srg.jar%23909!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23909!/:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by Jake-Samuels** [comment]
Just had a similar error occur in ATM9- all of the recipes from 2 netherite crafters were deleted:
```
[11:58:17] [Server thread/INFO]: Made Refined Storage shape cache map thread-safe
[11:58:19] [Server thread/ERROR]: Exception during multithreaded recipe lookup
[11:58:19] [Server thread/ERROR]: Could not read network node
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.util.ConcurrentModificationException: java.util.ConcurrentModificationException
	at dev.shadowsoffire.fastsuite.AuxRecipeManager.m_44015_(AuxRecipeManager.java:49) ~[FastSuite-1.20.1-5.0.1.jar%23681!/:5.0.1]
	at com.refinedmods.refinedstorage.apiimpl.autocrafting.CraftingPatternFactory.create(CraftingPatternFactory.java:60) ~[refinedstorage-1.12.3.jar%23824!/:?]
	at com.refinedmods.refinedstorage.item.PatternItem.create(PatternItem.java:293) ~[refinedstorage-1.12.3.jar%23824!/:?]
	at edivad.extrastorage.nodes.AdvancedCrafterNetworkNode.invalidateSlot(AdvancedCrafterNetworkNode.java:127) ~[ExtraStorage-1.20.1-4.0.3.jar%23673!/:1.20.1-4.0.3]
	at edivad.extrastorage.nodes.AdvancedCrafterNetworkNode.invalidate(AdvancedCrafterNetworkNode.java:114) ~[ExtraStorage-1.20.1-4.0.3.jar%23673!/:1.20.1-4.0.3]
	at edivad.extrastorage.nodes.AdvancedCrafterNetworkNode.read(AdvancedCrafterNetworkNode.java:191) ~[ExtraStorage-1.20.1-4.0.3.jar%23673!/:1.20.1-4.0.3]
	at edivad.extrastorage.ExtraStorage.readAndReturn(ExtraStorage.java:80) ~[ExtraStorage-1.20.1-4.0.3.jar%23673!/:1.20.1-4.0.3]
	at edivad.extrastorage.ExtraStorage.lambda$handleCommonSetup$1(ExtraStorage.java:114) ~[ExtraStorage-1.20.1-4.0.3.jar%23673!/:1.20.1-4.0.3]
	at com.refinedmods.refinedstorage.apiimpl.network.NetworkNodeManager.load(NetworkNodeManager.java:59) ~[refinedstorage-1.12.3.jar%23824!/:?]
	at com.refinedmods.refinedstorage.apiimpl.API.lambda$getNetworkNodeManager$1(API.java:134) ~[refinedstorage-1.12.3.jar%23824!/:?]
	at net.minecraft.world.level.storage.DimensionDataStorage.m_164868_(DimensionDataStorage.java:70) ~[client-1.20.1-20230612.114412-srg.jar%23918!/:?]
	at net.minecraft.world.level.storage.DimensionDataStorage.m_164858_(DimensionDataStorage.java:54) ~[client-1.20.1-20230612.114412-srg.jar%23918!/:?]
	at net.minecraft.world.level.storage.DimensionDataStorage.m_164861_(DimensionDataStorage.java:39) ~[client-1.20.1-20230612.114412-srg.jar%23918!/:?]
	at com.refinedmods.refinedstorage.apiimpl.API.getNetworkNodeManager(API.java:132) ~[refinedstorage-1.12.3.jar%23824!/:?]
	at com.refinedmods.refinedstorage.blockentity.NetworkNodeBlockEntity.m_6339_(NetworkNodeBlockEntity.java:94) ~[refinedstorage-1.12.3.jar%23824!/:?]
	at net.minecraft.world.level.chunk.LevelChunk.m_142169_(LevelChunk.java:362) ~[client-1.20.1-20230612.114412-srg.jar%23918!/:?]
	at net.minecraft.world.level.chunk.storage.ChunkSerializer.m_196900_(ChunkSerializer.java:404) ~[client-1.20.1-20230612.114412-srg.jar%23918!/:?]
	at net.minecraft.world.level.chunk.LevelChunk.m_62952_(LevelChunk.java:438) ~[client-1.20.1-20230612.114412-srg.jar%23918!/:?]
	at net.minecraft.server.level.ChunkMap.mixinextras$bridge$m_62952_$151(ChunkMap.java) ~[client-1.20.1-20230612.114412-srg.jar%23918!/:?]
	at net.minecraft.server.level.ChunkMap.wrapOperation$zfl000$setCurrentLoadingThenPostLoad(ChunkMap.java:1905) ~[client-1.20.1-20230612.114412-srg.jar%23918!/:?]
	at net.minecraft.server.level.ChunkMap.m_214854_(ChunkMap.java:715) ~[client-1.20.1-20230612.114412-srg.jar%23918!/:?]
	at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162) ~[datafixerupper-6.0.8.jar%23114!/:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar%23114!/:?]
	at com.mojang.datafixers.util.Either.mapLeft(Either.java:162) ~[datafixerupper-6.0.8.jar%23114!/:?]
	at net.minecraft.server.level.ChunkMap.m_287044_(ChunkMap.java:699) ~[client-1.20.1-20230612.114412-srg.jar%23918!/:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[client-1.20.1-20230612.114412-srg.jar%23918!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[client-1.20.1-20230612.114412-srg.jar%23918!/:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_6367_(ServerChunkCache.java:541) ~[client-1.20.1-20230612.114412-srg.jar%23918!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[client-1.20.1-20230612.114412-srg.jar%23918!/:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_7245_(ServerChunkCache.java:549) ~[client-1.20.1-20230612.114412-srg.jar%23918!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_8466_(ServerChunkCache.java:269) ~[client-1.20.1-20230612.114412-srg.jar%23918!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:758) ~[client-1.20.1-20230612.114412-srg.jar%23918!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747) ~[client-1.20.1-20230612.114412-srg.jar%23918!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139) ~[client-1.20.1-20230612.114412-srg.jar%23918!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:733) ~[client-1.20.1-20230612.114412-srg.jar%23918!/:?]
	at net.minecraft.server.MinecraftServer.m_129940_(MinecraftServer.java:459) ~[client-1.20.1-20230612.114412-srg.jar%23918!/:?]
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:310) ~[client-1.20.1-20230612.114412-srg.jar%23918!/:?]
	at net.minecraft.client.server.IntegratedServer.m_7038_(IntegratedServer.java:63) ~[client-1.20.1-20230612.114412-srg.jar%23918!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:634) ~[client-1.20.1-20230612.114412-srg.jar%23918!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23918!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.util.ConcurrentModificationException: java.util.ConcurrentModificationException
	at dev.shadowsoffire.fastsuite.StreamUtils.executeUntil(StreamUtils.java:116) ~[FastSuite-1.20.1-5.0.1.jar%23681!/:5.0.1]
	at dev.shadowsoffire.fastsuite.AuxRecipeManager.m_44015_(AuxRecipeManager.java:44) ~[FastSuite-1.20.1-5.0.1.jar%23681!/:5.0.1]
	... 42 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.util.ConcurrentModificationException: java.util.ConcurrentModificationException
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:562) ~[?:?]
	at java.util.concurrent.ForkJoinTask.reportExecutionException(ForkJoinTask.java:604) ~[?:?]
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1004) ~[?:?]
	at dev.shadowsoffire.fastsuite.StreamUtils.executeUntil(StreamUtils.java:105) ~[FastSuite-1.20.1-5.0.1.jar%23681!/:5.0.1]
	at dev.shadowsoffire.fastsuite.AuxRecipeManager.m_44015_(AuxRecipeManager.java:44) ~[FastSuite-1.20.1-5.0.1.jar%23681!/:5.0.1]
	... 42 more
Caused by: java.lang.RuntimeException: java.util.ConcurrentModificationException: java.util.ConcurrentModificationException
	at dev.shadowsoffire.fastsuite.StreamUtils$CallableExecuteAction.exec(StreamUtils.java:174) ~[FastSuite-1.20.1-5.0.1.jar%23681!/:5.0.1]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.util.ConcurrentModificationException: java.util.ConcurrentModificationException
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:562) ~[?:?]
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:591) ~[?:?]
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:689) ~[?:?]
	at java.util.stream.FindOps$FindOp.evaluateParallel(FindOps.java:160) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[?:?]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[?:?]
	at dev.shadowsoffire.fastsuite.AuxRecipeManager.lambda$getRecipeFor$1(AuxRecipeManager.java:46) ~[FastSuite-1.20.1-5.0.1.jar%23681!/:5.0.1]
	at dev.shadowsoffire.fastsuite.StreamUtils$CallableExecuteAction.exec(StreamUtils.java:171) ~[FastSuite-1.20.1-5.0.1.jar%23681!/:5.0.1]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap.computeIfAbsent(HashMap.java:1221) ~[?:?]
	at mekanism.common.block.attribute.AttributeTier.getPassthroughType(AttributeTier.java:16) ~[Mekanism-1.20.1-10.4.2.16.jar%23764!/:10.4.2]
	at mekanism.common.block.transmitter.BlockUniversalCable.getType(BlockUniversalCable.java:29) ~[Mekanism-1.20.1-10.4.2.16.jar%23764!/:10.4.2]
	at mekanism.common.block.attribute.Attribute.has(Attribute.java:31) ~[Mekanism-1.20.1-10.4.2.16.jar%23764!/:10.4.2]
	at mekanism.common.item.block.ItemBlockMekanism.exposesEnergyCap(ItemBlockMekanism.java:114) ~[Mekanism-1.20.1-10.4.2.16.jar%23764!/:10.4.2]
	at mekanism.common.item.block.ItemBlockMekanism.areCapabilityConfigsLoaded(ItemBlockMekanism.java:118) ~[Mekanism-1.20.1-10.4.2.16.jar%23764!/:10.4.2]
	at mekanism.common.item.block.ItemBlockMekanism.initCapabilities(ItemBlockMekanism.java:126) ~[Mekanism-1.20.1-10.4.2.16.jar%23764!/:10.4.2]
	at net.minecraft.world.item.ItemStack.lambda$forgeInit$10(ItemStack.java:992) ~[client-1.20.1-20230612.114412-srg.jar%23918!/:?]
	at net.minecraftforge.common.capabilities.CapabilityProvider.getCapabilities(CapabilityProvider.java:87) ~[forge-1.20.1-47.1.3-universal.jar%23923!/:?]
	at net.minecraftforge.common.capabilities.CapabilityProvider.getCapability(CapabilityProvider.java:182) ~[forge-1.20.1-47.1.3-universal.jar%23923!/:?]
	at net.minecraftforge.common.capabilities.ICapabilityProvider.getCapability(ICapabilityProvider.java:33) ~[forge-1.20.1-47.1.3-universal.jar%23923!/:?]
	at com.enderio.base.common.recipe.ShapedEntityStorageRecipe.getInputEntityStorage(ShapedEntityStorageRecipe.java:61) ~[EnderIO-1.20.1-6.0.21-alpha.jar%23659!/:6.0.21-alpha]
	at com.enderio.base.common.recipe.ShapedEntityStorageRecipe.m_5818_(ShapedEntityStorageRecipe.java:54) ~[EnderIO-1.20.1-6.0.21-alpha.jar%23659!/:6.0.21-alpha]
	at com.enderio.base.common.recipe.ShapedEntityStorageRecipe.m_5818_(ShapedEntityStorageRecipe.java:24) ~[EnderIO-1.20.1-6.0.21-alpha.jar%23659!/:6.0.21-alpha]
	at dev.shadowsoffire.fastsuite.AuxRecipeManager.lambda$getRecipeFor$0(AuxRecipeManager.java:45) ~[FastSuite-1.20.1-5.0.1.jar%23681!/:5.0.1]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?]
	at java.util.HashMap$ValueSpliterator.tryAdvance(HashMap.java:1800) ~[?:?]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.FindOps$FindTask.doLeaf(FindOps.java:319) ~[?:?]
	at java.util.stream.AbstractShortCircuitTask.compute(AbstractShortCircuitTask.java:115) ~[?:?]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
```

**Comment by Edivad99** [comment]
@baalus @Jakeyjuju  I think this is a problem of https://github.com/Shadows-of-Fire/FastSuite

**Comment by raoulvdberge** [comment]
``` 
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap.computeIfAbsent(HashMap.java:1221) ~[?:?]
	at mekanism.common.block.attribute.AttributeTier.getPassthroughType(AttributeTier.java:16) ~[Mekanism-1.20.1-10.4.2.16.jar%23764!/:10.4.2]
	at mekanism.common.block.transmitter.BlockUniversalCable.getType(BlockUniversalCable.java:29) ~[Mekanism-1.20.1-10.4.2.16.jar%23764!/:10.4.2]
	at mekanism.common.block.attribute.Attribute.has(Attribute.java:31) ~[Mekanism-1.20.1-10.4.2.16.jar%23764!/:10.4.2]
	at mekanism.common.item.block.ItemBlockMekanism.exposesEnergyCap(ItemBlockMekanism.java:114) ~[Mekanism-1.20.1-10.4.2.16.jar%23764!/:10.4.2]
	at mekanism.common.item.block.ItemBlockMekanism.areCapabilityConfigsLoaded(ItemBlockMekanism.java:118) ~[Mekanism-1.20.1-10.4.2.16.jar%23764!/:10.4.2]
	at mekanism.common.item.block.ItemBlockMekanism.initCapabilities(ItemBlockMekanism.java:126) ~[Mekanism-1.20.1-10.4.2.16.jar%23764!/:10.4.2]
	at net.minecraft.world.item.ItemStack.lambda$forgeInit$10(ItemStack.java:992) ~[client-1.20.1-20230612.114412-srg.jar%23918!/:?]
	at net.minecraftforge.common.capabilities.CapabilityProvider.getCapabilities(CapabilityProvider.java:87) ~[forge-1.20.1-47.1.3-universal.jar%23923!/:?]
	at net.minecraftforge.common.capabilities.CapabilityProvider.getCapability(CapabilityProvider.java:182) ~[forge-1.20.1-47.1.3-universal.jar%23923!/:?]
	at net.minecraftforge.common.capabilities.ICapabilityProvider.getCapability(ICapabilityProvider.java:33) ~[forge-1.20.1-47.1.3-universal.jar%23923!/:?]
	at com.enderio.base.common.recipe.ShapedEntityStorageRecipe.getInputEntityStorage(ShapedEntityStorageRecipe.java:61) ~[EnderIO-1.20.1-6.0.21-alpha.jar%23659!/:6.0.21-alpha]
	at com.enderio.base.common.recipe.ShapedEntityStorageRecipe.m_5818_(ShapedEntityStorageRecipe.java:54) ~[EnderIO-1.20.1-6.0.21-alpha.jar%23659!/:6.0.21-alpha]
	at com.enderio.base.common.recipe.ShapedEntityStorageRecipe.m_5818_(ShapedEntityStorageRecipe.java:24) ~[EnderIO-1.20.1-6.0.21-alpha.jar%23659!/:6.0.21-alpha]
	at dev.shadowsoffire.fastsuite.AuxRecipeManager.lambda$getRecipeFor$0(AuxRecipeManager.java:45) ~[FastSuite-1.20.1-5.0.1.jar%23681!/:5.0.1]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?]
	at java.util.HashMap$ValueSpliterator.tryAdvance(HashMap.java:1800) ~[?:?]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.FindOps$FindTask.doLeaf(FindOps.java:319) ~[?:?]
	at java.util.stream.AbstractShortCircuitTask.compute(AbstractShortCircuitTask.java:115) ~[?:?]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
```

Is a Mekanism issue

**Comment by raoulvdberge** [comment]
Reported https://github.com/mekanism/Mekanism/issues/8018
