### ISSUE TITLE
Cannot invoke "net.minecraft.core.Direction.m_122429_()" because "p_121946_" is null

### ISSUE THREAD

**Issue by 0xN0x** [Edivad99/ExtraStorage#80]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

My server crash when starting with an error coming from ExtraStorage

### How can I reproduce this bug or crash?

I don't know

### Configuration

```markdown
- Mod version: 4.0.5
- Refined Storage version: 1.12.4
- Forge version: 47.2.19
- Minecraft version: 1.20.1
- Modpack used : All the Mods 9 - 0.2.39
- Running on a server
```

### Relevant log output

```shell
minecraft-server-1  | [11:27:53] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
minecraft-server-1  | java.lang.NullPointerException: Cannot invoke "net.minecraft.core.Direction.m_122429_()" because "p_121946_" is null
minecraft-server-1  |   at net.minecraft.core.BlockPos.m_121945_(BlockPos.java:211) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?] {re:mixin,re:classloading}
minecraft-server-1  |   at edivad.extrastorage.nodes.AdvancedCrafterNetworkNode.getRootContainer(AdvancedCrafterNetworkNode.java:383) ~[ExtraStorage-1.20.1-4.0.5.jar%23640!/:1.20.1-4.0.5] {re:classloading}
minecraft-server-1  |   at edivad.extrastorage.nodes.AdvancedCrafterNetworkNode.getRootContainer(AdvancedCrafterNetworkNode.java:390) ~[ExtraStorage-1.20.1-4.0.5.jar%23640!/:1.20.1-4.0.5] {re:classloading}
minecraft-server-1  |   at edivad.extrastorage.nodes.AdvancedCrafterNetworkNode.getName(AdvancedCrafterNetworkNode.java:317) ~[ExtraStorage-1.20.1-4.0.5.jar%23640!/:1.20.1-4.0.5] {re:classloading}
minecraft-server-1  |   at com.refinedmods.refinedstorage.apiimpl.autocrafting.CraftingManager.invalidate(CraftingManager.java:437) ~[refinedstorage-1.12.4.jar%23799!/:?] {re:classloading}
minecraft-server-1  |   at edivad.extrastorage.nodes.AdvancedCrafterNetworkNode.onConnectedStateChange(AdvancedCrafterNetworkNode.java:168) ~[ExtraStorage-1.20.1-4.0.5.jar%23640!/:1.20.1-4.0.5] {re:classloading}
minecraft-server-1  |   at com.refinedmods.refinedstorage.apiimpl.network.node.NetworkNode.onConnected(NetworkNode.java:96) ~[refinedstorage-1.12.4.jar%23799!/:?] {re:classloading,re:mixin}
minecraft-server-1  |   at com.refinedmods.refinedstorage.apiimpl.network.NetworkNodeGraph.invalidate(NetworkNodeGraph.java:49) ~[refinedstorage-1.12.4.jar%23799!/:?] {re:classloading}
minecraft-server-1  |   at com.refinedmods.refinedstorage.apiimpl.network.Network.update(Network.java:210) ~[refinedstorage-1.12.4.jar%23799!/:?] {re:classloading}
minecraft-server-1  |   at com.refinedmods.refinedstorage.apiimpl.network.NetworkListener.onLevelTick(NetworkListener.java:17) ~[refinedstorage-1.12.4.jar%23799!/:?] {re:classloading}
minecraft-server-1  |   at com.refinedmods.refinedstorage.apiimpl.network.__NetworkListener_onLevelTick_LevelTickEvent.invoke(.dynamic) ~[refinedstorage-1.12.4.jar%23799!/:?] {re:classloading,pl:eventbus:B}
minecraft-server-1  |   at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2352!/:?] {}
minecraft-server-1  |   at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2352!/:?] {}
minecraft-server-1  |   at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2352!/:?] {}
minecraft-server-1  |   at net.minecraftforge.event.ForgeEventFactory.onPostLevelTick(ForgeEventFactory.java:930) ~[forge-1.20.1-47.2.19-universal.jar%23910!/:?] {re:mixin,re:classloading,pl:mixin:APP:aether.mixins.json:common.ForgeEventFactoryMixin,pl:mixin:A}
minecraft-server-1  |   at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:899) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:gtceu-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:A}
minecraft-server-1  |   at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:lithostitched.mixins.json:server.DedicatedServerMixin,pl:mixin:APP:mixins/common/nochatreports.mixins.json:server.MixinDedicatedServer,pl:mixin:APP:tombstone.mixins.json:DedicatedServerMixin,pl:mixin:A}
minecraft-server-1  |   at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:gtceu-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:A}
minecraft-server-1  |   at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:gtceu-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:A}
minecraft-server-1  |   at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:gtceu-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:A}
minecraft-server-1  |   at java.lang.Thread.run(Unknown Source) ~[?:?] {re:mixin}
```

### Anything else?

An issue already exist for this (#67), but was closed as completed without any information or fix so i opened a new one expecting to get a solution

**Comment by Edivad99** [comment]
Tell me what block the crafter was pointing for

**Comment by 0xN0x** [comment]
I don't know as i can't start the server, maybe pointing on a fluxduct or a cable of refined storage but not 100% sure

**Comment by Edivad99** [comment]
Not very useful then

**Comment by 0xN0x** [comment]
It was pointing to a Thermal Series fluxduct

**Comment by Edivad99** [comment]
![2024-02-18_16 57 16](https://github.com/Edivad99/ExtraStorage/assets/25778604/c285ad54-ed33-4142-a96c-eef2dc919dc5)
![2024-02-18_16 57 10](https://github.com/Edivad99/ExtraStorage/assets/25778604/fa3d1125-114b-4cdb-9244-bb103a94ef73)
Like this?

**Comment by Edivad99** [comment]
@0xN0x ^

**Comment by Edivad99** [comment]
Should be fixed in the version that I just released.
